sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: XlQt9nDPYfgoXsSAzkKMbeUDG68ysVh3uuT1p9VQ5cGK/X1A/5uzshk+lP2ePFfV7Z/9AZS43vO5knoNHvsZbJdpAfgPx/38+2YTFO0k9yAoN6L3kHsaryiuLVLbEsMrzJ9+D7TU/I6s8mUghNvLKcMMuh73DaxrGt2HZvDfs7B9Ju1fDBbKnN3jQlUdTUXaRFo0wUGC6ePJftJszHavtgMFqK8Vbn2lopAXxqpvao1hBKspAhPGzmYjv24WYDhZIFhqyeNDaok6hM+tJt0kAXn8Ezq68UUbGm/4gEZpd2WGzshWZS8OesFCrlfUJujOizTfHsY4rhfJJre0MTINutdRV9/QS2Xuq0fLDRkyxfY1rfK/A9LzQbXfdpwqepjRRMyBShCbqR1APNaj3WA5C2o2F/8e2vlyFh9MxQnOC67R6xPIDNh4E+sNuhm/Ew0nGn2kp/NNWC7pl5Yzpmj/rtDEreDBYqxq5zV2cEgkhY1k1XZQvGtOrI4l4D3uyX02IjV2SapY0urTULF+M2CsXrlhiIuOsEoK50Fc68xdTe27B/jxQi9KjtjFC78+a5lXIGYSnfHF0oP+pEaiOUaTLbMm+VOqFUrFwZZzJz2d7/aXze3SqGw8Fvxmth0vQse81+TEzMYPCZOas5OmSYXzfXWhgO+1K3RpO+EvbyTiLOw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Child-Christopher-and-Goldilind-the-Fair_234
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy